services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: friend-map-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/init.sql:/docker-entrypoint-initdb.d/2-init.sql
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # PostgREST API Server
  postgrest:
    image: postgrest/postgrest:latest
    container_name: friend-map-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://anon:${POSTGREST_DB_PASSWORD:-mysecretpassword}@db:5432/postgres
      PGRST_DB_SCHEMA: api
      PGRST_DB_ANON_ROLE: anon
      PGRST_MAX_ROWS: 1000
    ports:
      - "${API_PORT:-3000}:3000"
    volumes:
      - ./db/postgrest.conf:/etc/postgrest.conf

volumes:
  postgres_data: